"""empty message

Revision ID: d8382a24ce3f
Revises: 
Create Date: 2022-05-30 16:55:33.569488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8382a24ce3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('identity_card', sa.String(length=12), nullable=True),
    sa.Column('mobile', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('identity_card'),
    sa.UniqueConstraint('mobile')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('identity_card', sa.String(length=12), nullable=True),
    sa.Column('mobile', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('total_sales', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('identity_card'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('username')
    )
    op.create_table('estate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('estate_type', sa.String(length=50), nullable=True),
    sa.Column('floor_space', sa.Float(), nullable=True),
    sa.Column('number_of_bedrooms', sa.Integer(), nullable=True),
    sa.Column('number_of_bathrooms', sa.Integer(), nullable=True),
    sa.Column('number_of_parking', sa.Integer(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('number_of_floors', sa.Integer(), nullable=True),
    sa.Column('number_of_unit_per_floor', sa.Integer(), nullable=True),
    sa.Column('elevator', sa.Boolean(), nullable=True),
    sa.Column('made_year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('postal_code')
    )
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estate_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('contract_type', sa.String(length=30), nullable=True),
    sa.Column('payment_amount', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('date_signed', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(length=500), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estate_owner',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('estate_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.PrimaryKeyConstraint('customer_id', 'estate_id')
    )
    op.create_table('customer_contract_buy',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('customer_id', 'contract_id')
    )
    op.create_table('customer_contract_sell',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('customer_id', 'contract_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_contract_sell')
    op.drop_table('customer_contract_buy')
    op.drop_table('estate_owner')
    op.drop_table('contract')
    op.drop_table('estate')
    op.drop_table('employee')
    op.drop_table('customer')
    # ### end Alembic commands ###
