# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys, os

from numpy import append
sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'app'))
import queries
from queries import *

from errorDialog import Ui_dialog as error

# import main as mainWin

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow

class Ui_dialog(object):

    def __init__(self):
        super(Ui_dialog, self).__init__()

    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(1300, 1000)
        dialog.setStyleSheet("/*scroll bar*/\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 50px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(85, 170, 255);\n"
"    min-width: 25px;\n"
"    border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 20px;\n"
"    margin: 21px 0px 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(85, 170, 255);\n"
"    min-height: 25px;\n"
"    border-radius: 7px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"QDialogButtonBox {\n"
"    border: 5px solid rgb(52, 59, 72);\n"
"    border-radius: 15px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    padding: 18px;\n"
"    margin: 0px 5px\n"
"}\n"
"QDialogButtonBox:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 5px solid rgb(61, 70, 86);\n"
"}\n"
"QDialogButtonBox:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 5px solid rgb(43, 50, 61);\n"
"}\n"
"\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(dialog)
        self.stackedWidget.setStyleSheet("*{\n"
"background-color: transparent;\n"
"color: #d2d2d2;\n"
"}\n"
"\n"
"#dialog, #centralWidget, #centralWidget_2,\n"
"#centralWidget_3,  #centralWidget_4\n"
"{\n"
"background-color: rgb(44, 49, 60);\n"
"}\n"
"\n"
"QScrollArea {\n"
"border: none;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.centralWidget = QtWidgets.QWidget(self.page)
        self.centralWidget.setStyleSheet("*{\n"
"background-color: transparent;\n"
"color: #d2d2d2;\n"
"}\n"
"\n"
"#dialog, #centralWidget{\n"
"background-color: rgb(44, 49, 60);\n"
"}\n"
"\n"
"QScrollArea {\n"
"border: none;\n"
"}\n"
"")
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.title_3 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title_3.setFont(font)
        self.title_3.setObjectName("title_3")
        self.verticalLayout_8.addWidget(self.title_3)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.centralWidget)
        self.scrollArea_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_3.sizePolicy().hasHeightForWidth())
        self.scrollArea_3.setSizePolicy(sizePolicy)
        self.scrollArea_3.setStyleSheet("")
        self.scrollArea_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrollArea_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea_3.setLineWidth(1)
        self.scrollArea_3.setMidLineWidth(0)
        self.scrollArea_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_3.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1236, 2381))
        self.scrollAreaWidgetContents_3.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 15px;\n"
"    border: 5px solid rgb(27, 29, 35);\n"
"    padding: 15px;\n"
"    padding-left: 20px;\n"
"    margin: 0px 20px 10px 20px\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 5px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 5px solid rgb(91, 101, 124);\n"
"}\n"
"")
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_44.setEnabled(True)
        self.lineEdit_44.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_44.setFont(font)
        self.lineEdit_44.setStyleSheet("")
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.verticalLayout_5.addWidget(self.lineEdit_44)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_5.addWidget(self.label_14)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_43.setEnabled(True)
        self.lineEdit_43.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_43.setFont(font)
        self.lineEdit_43.setStyleSheet("")
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.verticalLayout_5.addWidget(self.lineEdit_43)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_5.addWidget(self.label_15)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_42.setEnabled(True)
        self.lineEdit_42.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_42.setFont(font)
        self.lineEdit_42.setStyleSheet("")
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.verticalLayout_5.addWidget(self.lineEdit_42)
        self.label_39 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_5.addWidget(self.label_39)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_41.setEnabled(True)
        self.lineEdit_41.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_41.setFont(font)
        self.lineEdit_41.setStyleSheet("")
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.verticalLayout_5.addWidget(self.lineEdit_41)
        self.label_41 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_5.addWidget(self.label_41)
        self.lineEdit_40 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_40.setEnabled(True)
        self.lineEdit_40.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_40.setFont(font)
        self.lineEdit_40.setStyleSheet("")
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.verticalLayout_5.addWidget(self.lineEdit_40)
        self.label_37 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_5.addWidget(self.label_37)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_39.setEnabled(True)
        self.lineEdit_39.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_39.setFont(font)
        self.lineEdit_39.setStyleSheet("")
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.verticalLayout_5.addWidget(self.lineEdit_39)
        self.label_44 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_5.addWidget(self.label_44)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_38.setEnabled(True)
        self.lineEdit_38.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_38.setFont(font)
        self.lineEdit_38.setStyleSheet("")
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.verticalLayout_5.addWidget(self.lineEdit_38)
        self.label_40 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_5.addWidget(self.label_40)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_37.setEnabled(True)
        self.lineEdit_37.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_37.setFont(font)
        self.lineEdit_37.setStyleSheet("")
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.verticalLayout_5.addWidget(self.lineEdit_37)
        self.label_42 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_5.addWidget(self.label_42)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_13.setEnabled(True)
        self.lineEdit_13.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setStyleSheet("")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.verticalLayout_5.addWidget(self.lineEdit_13)
        self.label_43 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_5.addWidget(self.label_43)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_14.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setStyleSheet("")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.verticalLayout_5.addWidget(self.lineEdit_14)
        self.label_38 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_5.addWidget(self.label_38)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_15.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setStyleSheet("")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.verticalLayout_5.addWidget(self.lineEdit_15)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_5.addWidget(self.label_16)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_16.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_16.setFont(font)
        self.lineEdit_16.setStyleSheet("")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.verticalLayout_5.addWidget(self.lineEdit_16)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_5.addWidget(self.label_17)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_17.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_17.setFont(font)
        self.lineEdit_17.setStyleSheet("")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.verticalLayout_5.addWidget(self.lineEdit_17)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_5.addWidget(self.label_18)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_18.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_18.setFont(font)
        self.lineEdit_18.setStyleSheet("")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.verticalLayout_5.addWidget(self.lineEdit_18)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_8.addWidget(self.scrollArea_3)
        self.buttonWidget_3 = QtWidgets.QWidget(self.centralWidget)
        self.buttonWidget_3.setStyleSheet("")
        self.buttonWidget_3.setObjectName("buttonWidget_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.buttonWidget_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.buttonBox_3 = QtWidgets.QDialogButtonBox(self.buttonWidget_3)
        self.buttonBox_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox_3.sizePolicy().hasHeightForWidth())
        self.buttonBox_3.setSizePolicy(sizePolicy)
        self.buttonBox_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.buttonBox_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.buttonBox_3.setAutoFillBackground(False)
        self.buttonBox_3.setStyleSheet("")
        self.buttonBox_3.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_3.button(QtWidgets.QDialogButtonBox.Ok).setText("Submit")
        self.buttonBox_3.setCenterButtons(True)
        self.buttonBox_3.setObjectName("buttonBox_3")
        self.buttonBox_3.setStyleSheet(
"       border: 5px solid rgb(52, 59, 72);\n"
"       border-radius: 15px;    \n"
"       background-color: rgb(52, 59, 72);\n"
"       padding: 18px;\n"
"       margin: 0px 5px\n"
        )
        self.verticalLayout_10.addWidget(self.buttonBox_3, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_8.addWidget(self.buttonWidget_3)
        self.verticalLayout_11.addWidget(self.centralWidget)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.centralWidget_2 = QtWidgets.QWidget(self.page_2)
        self.centralWidget_2.setStyleSheet("\n"
"")
        self.centralWidget_2.setObjectName("centralWidget_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.centralWidget_2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.title_4 = QtWidgets.QLabel(self.centralWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title_4.setFont(font)
        self.title_4.setObjectName("title_4")
        self.verticalLayout_12.addWidget(self.title_4)
        self.scrollArea_4 = QtWidgets.QScrollArea(self.centralWidget_2)
        self.scrollArea_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_4.sizePolicy().hasHeightForWidth())
        self.scrollArea_4.setSizePolicy(sizePolicy)
        self.scrollArea_4.setStyleSheet("")
        self.scrollArea_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrollArea_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea_4.setLineWidth(1)
        self.scrollArea_4.setMidLineWidth(0)
        self.scrollArea_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_4.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, -276, 1236, 1037))
        self.scrollAreaWidgetContents_4.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 15px;\n"
"    border: 5px solid rgb(27, 29, 35);\n"
"    padding: 15px;\n"
"    padding-left: 20px;\n"
"    margin: 0px 20px 10px 20px\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 5px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 5px solid rgb(91, 101, 124);\n"
"}\n"
"")
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_13.setContentsMargins(-1, -1, 22, -1)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_19.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_13.addWidget(self.label_19)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit_19.setEnabled(True)
        self.lineEdit_19.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_19.setFont(font)
        self.lineEdit_19.setStyleSheet("")
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.verticalLayout_13.addWidget(self.lineEdit_19)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_13.addWidget(self.label_20)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit_20.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_20.setFont(font)
        self.lineEdit_20.setStyleSheet("")
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.verticalLayout_13.addWidget(self.lineEdit_20)
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_13.addWidget(self.label_21)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit_21.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_21.setFont(font)
        self.lineEdit_21.setStyleSheet("")
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.verticalLayout_13.addWidget(self.lineEdit_21)
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_13.addWidget(self.label_22)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit_22.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_22.setFont(font)
        self.lineEdit_22.setStyleSheet("")
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.verticalLayout_13.addWidget(self.lineEdit_22)
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_13.addWidget(self.label_23)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit_23.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_23.setFont(font)
        self.lineEdit_23.setStyleSheet("")
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.verticalLayout_13.addWidget(self.lineEdit_23)
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_13.addWidget(self.label_24)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit_24.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_24.setFont(font)
        self.lineEdit_24.setStyleSheet("")
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.verticalLayout_13.addWidget(self.lineEdit_24)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_12.addWidget(self.scrollArea_4)
        self.buttonWidget_4 = QtWidgets.QWidget(self.centralWidget_2)
        self.buttonWidget_4.setStyleSheet("")
        self.buttonWidget_4.setObjectName("buttonWidget_4")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.buttonWidget_4)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.buttonBox_4 = QtWidgets.QDialogButtonBox(self.buttonWidget_4)
        self.buttonBox_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox_4.sizePolicy().hasHeightForWidth())
        self.buttonBox_4.setSizePolicy(sizePolicy)
        self.buttonBox_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.buttonBox_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.buttonBox_4.setAutoFillBackground(False)
        self.buttonBox_4.setStyleSheet("")
        self.buttonBox_4.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_4.button(QtWidgets.QDialogButtonBox.Ok).setText("Submit")
        self.buttonBox_4.setCenterButtons(True)
        self.buttonBox_4.setObjectName("buttonBox_4")
        self.buttonBox_4.setStyleSheet(
"       border: 5px solid rgb(52, 59, 72);\n"
"       border-radius: 15px;    \n"
"       background-color: rgb(52, 59, 72);\n"
"       padding: 18px;\n"
"       margin: 0px 5px\n"
        )
        self.verticalLayout_14.addWidget(self.buttonBox_4, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_12.addWidget(self.buttonWidget_4)
        self.verticalLayout_2.addWidget(self.centralWidget_2)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.centralWidget_3 = QtWidgets.QWidget(self.page_3)
        self.centralWidget_3.setStyleSheet("\n"
"")
        self.centralWidget_3.setObjectName("centralWidget_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.centralWidget_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.title_5 = QtWidgets.QLabel(self.centralWidget_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title_5.setFont(font)
        self.title_5.setObjectName("title_5")
        self.verticalLayout_9.addWidget(self.title_5)
        self.scrollArea_5 = QtWidgets.QScrollArea(self.centralWidget_3)
        self.scrollArea_5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_5.sizePolicy().hasHeightForWidth())
        self.scrollArea_5.setSizePolicy(sizePolicy)
        self.scrollArea_5.setStyleSheet("")
        self.scrollArea_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrollArea_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea_5.setLineWidth(1)
        self.scrollArea_5.setMidLineWidth(0)
        self.scrollArea_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_5.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 1236, 1877))
        self.scrollAreaWidgetContents_5.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 15px;\n"
"    border: 5px solid rgb(27, 29, 35);\n"
"    padding: 15px;\n"
"    padding-left: 20px;\n"
"    margin: 0px 20px 10px 20px\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 5px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 5px solid rgb(91, 101, 124);\n"
"}\n"
"")
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_47 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_7.addWidget(self.label_47)
        self.lineEdit_49 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.lineEdit_49.setEnabled(True)
        self.lineEdit_49.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_49.setFont(font)
        self.lineEdit_49.setStyleSheet("")
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.verticalLayout_7.addWidget(self.lineEdit_49)
        self.label_48 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.verticalLayout_7.addWidget(self.label_48)
        self.lineEdit_48 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.lineEdit_48.setEnabled(True)
        self.lineEdit_48.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_48.setFont(font)
        self.lineEdit_48.setStyleSheet("")
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.verticalLayout_7.addWidget(self.lineEdit_48)
        self.label_27 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_7.addWidget(self.label_27)
        self.lineEdit_47 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.lineEdit_47.setEnabled(True)
        self.lineEdit_47.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_47.setFont(font)
        self.lineEdit_47.setStyleSheet("")
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.verticalLayout_7.addWidget(self.lineEdit_47)
        self.label_46 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_7.addWidget(self.label_46)
        self.lineEdit_46 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.lineEdit_46.setEnabled(True)
        self.lineEdit_46.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_46.setFont(font)
        self.lineEdit_46.setStyleSheet("")
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.verticalLayout_7.addWidget(self.lineEdit_46)
        self.label_26 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_7.addWidget(self.label_26)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.lineEdit_26.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_26.setFont(font)
        self.lineEdit_26.setStyleSheet("")
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.verticalLayout_7.addWidget(self.lineEdit_26)
        self.label_45 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_7.addWidget(self.label_45)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.lineEdit_27.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_27.setFont(font)
        self.lineEdit_27.setStyleSheet("")
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.verticalLayout_7.addWidget(self.lineEdit_27)
        self.label_28 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_7.addWidget(self.label_28)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.lineEdit_28.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_28.setFont(font)
        self.lineEdit_28.setStyleSheet("")
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.verticalLayout_7.addWidget(self.lineEdit_28)
        self.label_30 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_7.addWidget(self.label_30)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.lineEdit_30.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_30.setFont(font)
        self.lineEdit_30.setStyleSheet("")
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.verticalLayout_7.addWidget(self.lineEdit_30)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout_9.addWidget(self.scrollArea_5)
        self.buttonWidget_5 = QtWidgets.QWidget(self.centralWidget_3)
        self.buttonWidget_5.setStyleSheet("")
        self.buttonWidget_5.setObjectName("buttonWidget_5")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.buttonWidget_5)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.buttonBox_5 = QtWidgets.QDialogButtonBox(self.buttonWidget_5)
        self.buttonBox_5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox_5.sizePolicy().hasHeightForWidth())
        self.buttonBox_5.setSizePolicy(sizePolicy)
        self.buttonBox_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.buttonBox_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.buttonBox_5.setAutoFillBackground(False)
        self.buttonBox_5.setStyleSheet("")
        self.buttonBox_5.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_5.button(QtWidgets.QDialogButtonBox.Ok).setText("Submit")
        self.buttonBox_5.setCenterButtons(True)
        self.buttonBox_5.setObjectName("buttonBox_5")
        self.buttonBox_5.setStyleSheet(
"       border: 5px solid rgb(52, 59, 72);\n"
"       border-radius: 15px;    \n"
"       background-color: rgb(52, 59, 72);\n"
"       padding: 18px;\n"
"       margin: 0px 5px\n"
        )
        self.verticalLayout_17.addWidget(self.buttonBox_5, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_9.addWidget(self.buttonWidget_5)
        self.verticalLayout_4.addWidget(self.centralWidget_3)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.centralWidget_4 = QtWidgets.QWidget(self.page_4)
        self.centralWidget_4.setStyleSheet("\n"
"")
        self.centralWidget_4.setObjectName("centralWidget_4")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.centralWidget_4)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.title_6 = QtWidgets.QLabel(self.centralWidget_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title_6.setFont(font)
        self.title_6.setObjectName("title_6")
        self.verticalLayout_18.addWidget(self.title_6)
        self.scrollArea_6 = QtWidgets.QScrollArea(self.centralWidget_4)
        self.scrollArea_6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_6.sizePolicy().hasHeightForWidth())
        self.scrollArea_6.setSizePolicy(sizePolicy)
        self.scrollArea_6.setStyleSheet("")
        self.scrollArea_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrollArea_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea_6.setLineWidth(1)
        self.scrollArea_6.setMidLineWidth(0)
        self.scrollArea_6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_6.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_6.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, -552, 1236, 1373))
        self.scrollAreaWidgetContents_6.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 15px;\n"
"    border: 5px solid rgb(27, 29, 35);\n"
"    padding: 15px;\n"
"    padding-left: 20px;\n"
"    margin: 0px 20px 10px 20px\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 5px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 5px solid rgb(91, 101, 124);\n"
"}\n"
"")
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_52 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.verticalLayout_6.addWidget(self.label_52)
        self.lineEdit_53 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.lineEdit_53.setEnabled(True)
        self.lineEdit_53.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_53.setFont(font)
        self.lineEdit_53.setStyleSheet("")
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.verticalLayout_6.addWidget(self.lineEdit_53)
        self.label_53 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.verticalLayout_6.addWidget(self.label_53)
        self.lineEdit_52 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.lineEdit_52.setEnabled(True)
        self.lineEdit_52.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_52.setFont(font)
        self.lineEdit_52.setStyleSheet("")
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.verticalLayout_6.addWidget(self.lineEdit_52)
        self.label_33 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_6.addWidget(self.label_33)
        self.lineEdit_51 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.lineEdit_51.setEnabled(True)
        self.lineEdit_51.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_51.setFont(font)
        self.lineEdit_51.setStyleSheet("")
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.verticalLayout_6.addWidget(self.lineEdit_51)
        self.label_51 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.verticalLayout_6.addWidget(self.label_51)
        self.lineEdit_50 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.lineEdit_50.setEnabled(True)
        self.lineEdit_50.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_50.setFont(font)
        self.lineEdit_50.setStyleSheet("")
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.verticalLayout_6.addWidget(self.lineEdit_50)
        self.label_31 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_31.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_6.addWidget(self.label_31)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.lineEdit_31.setEnabled(True)
        self.lineEdit_31.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_31.setFont(font)
        self.lineEdit_31.setStyleSheet("")
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.verticalLayout_6.addWidget(self.lineEdit_31)
        self.label_32 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_6.addWidget(self.label_32)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.lineEdit_32.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_32.setFont(font)
        self.lineEdit_32.setStyleSheet("")
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.verticalLayout_6.addWidget(self.lineEdit_32)
        self.label_50 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.verticalLayout_6.addWidget(self.label_50)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.lineEdit_33.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_33.setFont(font)
        self.lineEdit_33.setStyleSheet("")
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.verticalLayout_6.addWidget(self.lineEdit_33)
        self.label_34 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_6.addWidget(self.label_34)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.lineEdit_34.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_34.setFont(font)
        self.lineEdit_34.setStyleSheet("")
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.verticalLayout_6.addWidget(self.lineEdit_34)
        self.label_35 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_6.addWidget(self.label_35)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.lineEdit_35.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_35.setFont(font)
        self.lineEdit_35.setStyleSheet("")
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.verticalLayout_6.addWidget(self.lineEdit_35)
        self.label_36 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_6.addWidget(self.label_36)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.lineEdit_36.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_36.setFont(font)
        self.lineEdit_36.setStyleSheet("")
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.verticalLayout_6.addWidget(self.lineEdit_36)
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_6)
        self.verticalLayout_18.addWidget(self.scrollArea_6)
        self.buttonWidget_6 = QtWidgets.QWidget(self.centralWidget_4)
        self.buttonWidget_6.setStyleSheet("")
        self.buttonWidget_6.setObjectName("buttonWidget_6")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.buttonWidget_6)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.buttonBox_6 = QtWidgets.QDialogButtonBox(self.buttonWidget_6)
        self.buttonBox_6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox_6.sizePolicy().hasHeightForWidth())
        self.buttonBox_6.setSizePolicy(sizePolicy)
        self.buttonBox_6.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.buttonBox_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.buttonBox_6.setAutoFillBackground(False)
        self.buttonBox_6.setStyleSheet("")
        self.buttonBox_6.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_6.button(QtWidgets.QDialogButtonBox.Ok).setText("Submit")
        self.buttonBox_6.setCenterButtons(True)
        self.buttonBox_6.setObjectName("buttonBox_6")
        self.buttonBox_6.setStyleSheet(
"       border: 5px solid rgb(52, 59, 72);\n"
"       border-radius: 15px;    \n"
"       background-color: rgb(52, 59, 72);\n"
"       padding: 18px;\n"
"       margin: 0px 5px\n"
        )
        self.verticalLayout_20.addWidget(self.buttonBox_6, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_18.addWidget(self.buttonWidget_6)
        self.verticalLayout_3.addWidget(self.centralWidget_4)
        self.stackedWidget.addWidget(self.page_4)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(dialog)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(dialog)

        # mainWind = mainWin.MainWindow(QMainWindow)
        try:
                self.buttonBox_3.accepted.connect(lambda: self.storeInputData(0))
                self.buttonBox_3.accepted.connect(dialog.accept)
                self.buttonBox_4.accepted.connect(lambda: self.storeInputData(1))
                self.buttonBox_4.accepted.connect(dialog.accept)
                self.buttonBox_5.accepted.connect(lambda: self.storeInputData(2))
                self.buttonBox_5.accepted.connect(dialog.accept)
                self.buttonBox_6.accepted.connect(lambda: self.storeInputData(3))
                self.buttonBox_6.accepted.connect(dialog.accept)
        except Exception as err:
            dialog.close()
            self.error_dialog()


        self.buttonBox_3.rejected.connect(dialog.reject)
        self.buttonBox_4.rejected.connect(dialog.reject)
        self.buttonBox_5.rejected.connect(dialog.reject)
        self.buttonBox_6.rejected.connect(dialog.reject)
        
        self.create = None


    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Dialog"))
        self.title_3.setText(_translate("dialog", "New Record"))
        self.label_13.setText(_translate("dialog", "Postal Code  (must be unique)"))
        self.lineEdit_44.setPlaceholderText(_translate("dialog", "input"))
        self.label_14.setText(_translate("dialog", "Owner Identity Card"))
        self.lineEdit_43.setPlaceholderText(_translate("dialog", "input"))
        self.label_15.setText(_translate("dialog", "Address"))
        self.lineEdit_42.setPlaceholderText(_translate("dialog", "input"))
        self.label_39.setText(_translate("dialog", "Estate Type"))
        self.lineEdit_41.setPlaceholderText(_translate("dialog", "input"))
        self.label_41.setText(_translate("dialog", "Floor Space"))
        self.lineEdit_40.setPlaceholderText(_translate("dialog", "input"))
        self.label_37.setText(_translate("dialog", "Number Of Bedrooms"))
        self.lineEdit_39.setPlaceholderText(_translate("dialog", "input"))
        self.label_44.setText(_translate("dialog", "Number of Bathrooms"))
        self.lineEdit_38.setPlaceholderText(_translate("dialog", "input"))
        self.label_40.setText(_translate("dialog", "Number Of Parkings"))
        self.lineEdit_37.setPlaceholderText(_translate("dialog", "input"))
        self.label_42.setText(_translate("dialog", "Floor"))
        self.lineEdit_13.setPlaceholderText(_translate("dialog", "input"))
        self.label_43.setText(_translate("dialog", "Number Of Floors"))
        self.lineEdit_14.setPlaceholderText(_translate("dialog", "input"))
        self.label_38.setText(_translate("dialog", "Number Of Unit Per Floor"))
        self.lineEdit_15.setPlaceholderText(_translate("dialog", "input"))
        self.label_16.setText(_translate("dialog", "Elavator (true/false)"))
        self.lineEdit_16.setPlaceholderText(_translate("dialog", "input"))
        self.label_17.setText(_translate("dialog", "Made Year"))
        self.lineEdit_17.setPlaceholderText(_translate("dialog", "input"))
        self.label_18.setText(_translate("dialog", "Description"))
        self.lineEdit_18.setPlaceholderText(_translate("dialog", "input"))
        self.title_4.setText(_translate("dialog", "New Record"))
        self.label_19.setText(_translate("dialog", "First Name"))
        self.lineEdit_19.setPlaceholderText(_translate("dialog", "input"))
        self.label_20.setText(_translate("dialog", "Last Name"))
        self.lineEdit_20.setPlaceholderText(_translate("dialog", "input"))
        self.label_21.setText(_translate("dialog", "Identity Card (must be unique)"))
        self.lineEdit_21.setPlaceholderText(_translate("dialog", "input"))
        self.label_22.setText(_translate("dialog", "Mobile (must be unique)"))
        self.lineEdit_22.setPlaceholderText(_translate("dialog", "input"))
        self.label_23.setText(_translate("dialog", "Email (must be unique)"))
        self.lineEdit_23.setPlaceholderText(_translate("dialog", "input"))
        self.label_24.setText(_translate("dialog", "Address"))
        self.lineEdit_24.setPlaceholderText(_translate("dialog", "input"))
        self.title_5.setText(_translate("dialog", "New Record"))
        self.label_47.setText(_translate("dialog", "Estate Postal Code"))
        self.lineEdit_49.setPlaceholderText(_translate("dialog", "input"))
        self.label_48.setText(_translate("dialog", "Employee Identity Card"))
        self.lineEdit_48.setPlaceholderText(_translate("dialog", "input"))
        self.label_27.setText(_translate("dialog", "Buyer Identity Card"))
        self.lineEdit_47.setPlaceholderText(_translate("dialog", "input"))
        self.label_46.setText(_translate("dialog", "Seller Identity Card"))
        self.lineEdit_46.setPlaceholderText(_translate("dialog", "input"))
        self.label_26.setText(_translate("dialog", "Contract Type (sell/buy/rent)"))
        self.lineEdit_26.setPlaceholderText(_translate("dialog", "input"))
        self.label_45.setText(_translate("dialog", "Payment Amount"))
        self.lineEdit_27.setPlaceholderText(_translate("dialog", "input"))
        self.label_28.setText(_translate("dialog", "Profit"))
        self.lineEdit_28.setPlaceholderText(_translate("dialog", "input"))
        self.label_30.setText(_translate("dialog", "Description"))
        self.lineEdit_30.setPlaceholderText(_translate("dialog", "input"))
        self.title_6.setText(_translate("dialog", "New Record"))
        self.label_33.setText(_translate("dialog", "First Name"))
        self.lineEdit_51.setPlaceholderText(_translate("dialog", "input"))
        self.label_51.setText(_translate("dialog", "Last Name"))
        self.lineEdit_50.setPlaceholderText(_translate("dialog", "input"))
        self.label_31.setText(_translate("dialog", "Identity Card  (must be unique)"))
        self.lineEdit_31.setPlaceholderText(_translate("dialog", "input"))
        self.label_32.setText(_translate("dialog", "Mobile (must be unique)"))
        self.lineEdit_32.setPlaceholderText(_translate("dialog", "input"))
        self.label_50.setText(_translate("dialog", "Email (must be unique)"))
        self.lineEdit_33.setPlaceholderText(_translate("dialog", "input"))
        self.label_34.setText(_translate("dialog", "Position"))
        self.lineEdit_34.setPlaceholderText(_translate("dialog", "input"))
        self.label_35.setText(_translate("dialog", "Salary"))
        self.lineEdit_35.setPlaceholderText(_translate("dialog", "input"))
        self.label_36.setText(_translate("dialog", "Total Sales"))
        self.lineEdit_36.setPlaceholderText(_translate("dialog", "input"))
        self.label_52.setText(_translate("dialog", "Username * (must be unique)"))
        self.lineEdit_53.setPlaceholderText(_translate("dialog", "input"))
        self.label_53.setText(_translate("dialog", "Password * (must be unique)"))
        self.lineEdit_52.setPlaceholderText(_translate("dialog", "input"))


    def storeInputData(self, index):
        self.inputsOf = index
        self.inputs = []
        match index:
                case 0:
                        self.inputs.append(self.lineEdit_44.text())
                        self.inputs.append(self.lineEdit_43.text())
                        self.inputs.append(self.lineEdit_42.text())
                        self.inputs.append(self.lineEdit_41.text())
                        self.inputs.append(self.lineEdit_40.text())
                        self.inputs.append(self.lineEdit_39.text())
                        self.inputs.append(self.lineEdit_38.text())
                        self.inputs.append(self.lineEdit_37.text())
                        self.inputs.append(self.lineEdit_13.text())
                        self.inputs.append(self.lineEdit_14.text())
                        self.inputs.append(self.lineEdit_15.text())
                        self.inputs.append(self.lineEdit_16.text())
                        self.inputs.append(self.lineEdit_17.text())
                        self.inputs.append(self.lineEdit_18.text())
                        self.create = True
                        self.createNewRecord()
                case 1:
                        self.inputs.append(self.lineEdit_19.text())
                        self.inputs.append(self.lineEdit_20.text())
                        self.inputs.append(self.lineEdit_21.text())
                        self.inputs.append(self.lineEdit_22.text())
                        self.inputs.append(self.lineEdit_23.text())
                        self.inputs.append(self.lineEdit_24.text())
                        self.create = True
                        self.createNewRecord()
                        
                case 2:
                        self.inputs.append(self.lineEdit_49.text())
                        self.inputs.append(self.lineEdit_48.text())
                        self.inputs.append(self.lineEdit_47.text())
                        self.inputs.append(self.lineEdit_46.text())
                        self.inputs.append(self.lineEdit_45.text())
                        self.inputs.append(self.lineEdit_25.text())
                        self.inputs.append(self.lineEdit_26.text())
                        self.inputs.append(self.lineEdit_27.text())
                        self.inputs.append(self.lineEdit_28.text())
                        self.inputs.append(self.lineEdit_29.text())
                        self.inputs.append(self.lineEdit_30.text())
                        self.create = True
                        self.createNewRecord()
                        
                case 3:
                        self.inputs.append(self.lineEdit_53.text())
                        self.inputs.append(self.lineEdit_52.text())
                        self.inputs.append(self.lineEdit_51.text())
                        self.inputs.append(self.lineEdit_50.text())
                        self.inputs.append(self.lineEdit_31.text())
                        self.inputs.append(self.lineEdit_32.text())
                        self.inputs.append(self.lineEdit_33.text())
                        self.inputs.append(self.lineEdit_34.text())
                        self.inputs.append(self.lineEdit_35.text())
                        self.inputs.append(self.lineEdit_36.text())
                        self.create = True
                        self.createNewRecord()
                        

        # print(self.inputs)

    def error_dialog(self):
        dialog = QtWidgets.QDialog()
        dialog.ui = error()
        dialog.ui.setupUi(dialog)
        dialog.exec_()
        dialog.show()

    def trueInputs(self):
        for pos, num in enumerate(self.inputs):
            if(num.replace('.', '', 1).isdigit() and not(num[0] == "0" and num[1])):
                self.inputs[pos] = float(num)
            if(num.isdigit() and not(num[0] == "0" and num[1])):
                self.inputs[pos] = int(num)
            if(num == ''):
                self.inputs[pos] = None
            #!
            if(num.lower() == 'true'):
                self.inputs[pos] = True
            if(num.lower() == 'false'):
                self.inputs[pos] = False
        print(self.inputs)
        return self.inputs

    def createNewRecord(self):
        input = self.trueInputs()
        match self.inputsOf:
            case 0:
                owner = []
                owner.append(input[1])
                try:
                        estate = queries.Estate()
                        estate.create(input[0], owner, input[2], input[3], input[4], input[5], input[6], input[7],
                        input[8], input[9], input[10], input[11], input[12], input[13])
                except Exception as err:
                        self.error_dialog()
            case 1:
                try:
                        customer = queries.Customer()
                        customer.create(input[0], input[1], input[2], input[3], input[4], input[5])
                except Exception as err:
                        self.error_dialog()
            case 2:
                buyer = []
                seller = []
                input[0] = str(input[0])
                buyer.append(input[2])
                seller.append(input[3])
                try:
                        contract = queries.Contract()
                        contract.create(input[0], input[1], buyer, seller, input[4], input[5], input[6])
                except Exception as err:
                        self.error_dialog()
            case 3:
                try:
                        employee = queries.Employee()
                        employee.create(input[0], input[1], input[2], input[3], input[4], input[5], input[6])
                except Exception as err:
                        self.error_dialog()
        self.create = False


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     dialog = QtWidgets.QDialog()
#     ui = Ui_dialog()
#     ui.setupUi(dialog)
#     dialog.show()
#     sys.exit(app.exec_())
