# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys, os
from PyQt5 import QtCore, QtGui, QtWidgets

sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'app'))
import models


class Ui_loginDialog(object):
    def setupUi(self, loginDialog):
        loginDialog.setObjectName("loginDialog")
        loginDialog.resize(1300, 1000)
        loginDialog.setStyleSheet("*{\n"
"background-color: transparent;\n"
"color: #d2d2d2;\n"
"}\n"
"\n"
"#loginDialog, #centralWidget{\n"
"background-color: rgb(44, 49, 60);\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(loginDialog)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.centralWidget = QtWidgets.QWidget(loginDialog)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("margin-top: 100px")
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.widget = QtWidgets.QWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(600, 400))
        self.widget.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 15px;\n"
"    border: 5px solid rgb(27, 29, 35);\n"
"    padding: 15px;\n"
"    padding-left: 20px;\n"
"    margin: 0px 20px 10px 20px\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 5px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 5px solid rgb(91, 101, 124);\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 22)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.usernameLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setObjectName("usernameLabel")
        self.verticalLayout_3.addWidget(self.usernameLabel)
        self.usernameLineEdit = QtWidgets.QLineEdit(self.widget)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.usernameLineEdit.setEnabled(True)
        self.verticalLayout_3.addWidget(self.usernameLineEdit)
        self.passwordLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setObjectName("passwordLabel")
        self.verticalLayout_3.addWidget(self.passwordLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.widget)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.passwordLineEdit.setEnabled(True)
        self.verticalLayout_3.addWidget(self.passwordLineEdit)
        self.verticalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.errorLabel = QtWidgets.QLabel(self.centralWidget)
        self.errorLabel.setObjectName("errorLabel")
        self.verticalLayout.addWidget(self.errorLabel, 0, QtCore.Qt.AlignHCenter)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralWidget)
        self.buttonBox.setStyleSheet("border: 5px solid rgb(52, 59, 72);\n"
"border-radius: 15px;\n"
"background-color: rgb(52, 59, 72);\n"
"padding: 18px;\n"
"margin: 0px 5px 30px 0px\n"
"")
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Ok).setText("Login")
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addWidget(self.centralWidget)

        self.user = []
        self.buttonBox.clicked.connect(lambda: self.loginData(loginDialog))
        self.retranslateUi(loginDialog)
        QtCore.QMetaObject.connectSlotsByName(loginDialog)

    def loginData(self, loginDialog):
        userFound = False
        self.user.append(self.usernameLineEdit.text())
        self.user.append(self.passwordLineEdit.text())

        for pos,num in enumerate(self.user):
            if(num==''):
                self.user[pos] = None
        
        employee = models.Employee.query.all()
        for row in employee:
                if(row.username == self.user[0] and row.password == self.user[1]):
                        # self.buttonBox.clicked.connect(loginDialog.accept)
                        userFound = True
        if(not userFound):
                print(self.user)
                self.errorLabel.setText("Incorrect username or password!")
                self.user.clear()
                self.passwordLineEdit.setReadOnly(False)

        else:
                #! not working if run by main
                loginDialog.close()
                

    def retranslateUi(self, loginDialog):
        _translate = QtCore.QCoreApplication.translate
        loginDialog.setWindowTitle(_translate("loginDialog", "Dialog"))
        self.titleLabel.setText(_translate("loginDialog", "LOGIN"))
        self.usernameLabel.setText(_translate("loginDialog", "username"))
        self.passwordLabel.setText(_translate("loginDialog", "password"))
        self.errorLabel.setText(_translate("loginDialog", ""))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     loginDialog = QtWidgets.QDialog()
#     ui = Ui_loginDialog()
#     ui.setupUi(loginDialog)
#     loginDialog.show()
#     sys.exit(app.exec_())
